module.exports = {
	clear: ['webapp/base-lib/lib'],
	copy: [{
		source: 'webapp-src/base-lib/lib/bootstrap/**/*',
		target: 'webapp/base-lib/lib/bootstrap/',
	}, {
		source: 'webapp-src/base-lib/lib/font-awesome/**/*',
		target: 'webapp/base-lib/lib/font-awesome/',
	}, {
		source: 'webapp-src/base-lib/lib/bootstrap-dialog/**/*',
		target: 'webapp/base-lib/lib/bootstrap-dialog/',
	}, {
		source: 'webapp-src/base-lib/lib/toastr/**/*',
		target: 'webapp/base-lib/lib/toastr/',
	}, {
		source: 'webapp-src/base-lib/lib/jquery/**/*',
		target: 'webapp/base-lib/lib/jquery/',
	}, {
		source: 'webapp-src/base-lib/lib/jquery-easyui/**/*',
		target: 'webapp/base-lib/lib/jquery-easyui/',
	}, {
		source: 'webapp-src/base-lib/lib/jquery-easyui/themes/**/*',
		target: 'webapp/base-lib/lib/jquery-easyui/themes/',
	}, {
		source: 'webapp-src/base-lib/lib/jquery-easyui/src/**/*',
		target: 'webapp/base-lib/lib/jquery-easyui/src/',
	}, {
		source: 'webapp-src/base-lib/lib/jquery-easyui/locale/**/*',
		target: 'webapp/base-lib/lib/jquery-easyui/locale/',
	}, {
		source: 'webapp-src/base-lib/lib/jquery-easyui/plugins/**/*',
		target: 'webapp/base-lib/lib/jquery-easyui/plugins/',
	}, {
		source: 'webapp-src/base-lib/lib/jquery-easyui/themes/icons/**/*',
		target: 'webapp/base-lib/lib/jquery-easyui/themes/icons/',
	}, {
		source: 'webapp-src/base-lib/lib/jquery-easyui/themes/default/**/*',
		target: 'webapp/base-lib/lib/jquery-easyui/themes/default/',
	}, {
		source: 'webapp-src/base-lib/lib/jquery-easyui/themes/default/images/**/*',
		target: 'webapp/base-lib/lib/jquery-easyui/themes/default/images/',
	}, {
		source: 'webapp-src/base-lib/lib/jquery-easyui/themes/material/**/*',
		target: 'webapp/base-lib/lib/jquery-easyui/themes/material/',
	}, {
		source: 'webapp-src/base-lib/lib/animate.css/*',
		target: 'webapp/base-lib/lib/animate.css/',
	}],
}
